### ISSUE TITLE
polish characters error

### ISSUE THREAD

**Issue by lkarthik76** [TomRoush/PdfBox-Android#100]
I am using default font ( PDFont font = PDType1Font.HELVETICA;). i am trying to add polish text contentStream.showText(" Dziewięćset "); its throwing error. PDF is not created.

**Comment by lkarthik76** [comment]
Error in details
Caused by: java.lang.IllegalArgumentException: This font type only supports 8-bit code points -No glyph for U+0119 in font Helvetica
                                                                               at com.tom_roush.pdfbox.pdmodel.font.PDType1Font.encode(PDType1Font.java:281)
                                                                               at com.tom_roush.pdfbox.pdmodel.font.PDFont.encode(PDFont.java:249)
                                                                               at com.tom_roush.pdfbox.pdmodel.PDPageContentStream.showText(PDPageContentStream.java:292)
                                                                               at com.tom_roush.pdfbox.sample.MainActivity.createPdf(MainActivity.java:104)

**Comment by TomRoush** [comment]
It sounds like Helvetica doesn't support Polish characters. LiberationSans, which is included with the library, will be able to write Polish. You could also add your own font file in the assets folder and load that instead.
`PDFont font = PDType0Font.load(document, assetManager.open("com/tom_roush/pdfbox/resources/ttf/LiberationSans-Regular.ttf"));`
