### ISSUE TITLE
java.lang.NullPointerException: Attempt to get length of null array

### ISSUE THREAD

**Issue by ToysoftInc** [TomRoush/PdfBox-Android#172]
When opening a pdf with annotations

eg:
			// Load in an already created PDF
			PDDocument document = PDDocument.load(assetManager.open("homework.pdf"));
			// Create a renderer for the document
			PDFRenderer renderer = new PDFRenderer(document);
			// Render the image to an RGB Bitmap
			pageImage = renderer.renderImage(0, 1, Bitmap.Config.RGB_565);

**Comment by ToysoftInc** [comment]
here is the stack trace.

Note: The PDF i'm trying to render has Annotations.


here is the pdf https://drive.google.com/open?id=1soSbpUrxZRdGjTIEIQTF_AP4LVeNi6nq

11-29 15:02:44.019 6345-6345/com.tom_roush.pdfbox.sample W/System.err: java.lang.NullPointerException: Attempt to get length of null array
        at android.graphics.DashPathEffect.<init>(DashPathEffect.java:35)
        at com.tom_roush.pdfbox.rendering.PageDrawer.setStroke(PageDrawer.java:566)
        at com.tom_roush.pdfbox.rendering.PageDrawer.strokePath(PageDrawer.java:575)
        at com.tom_roush.pdfbox.contentstream.operator.graphics.StrokePath.process(StrokePath.java:20)
        at com.tom_roush.pdfbox.contentstream.PDFStreamEngine.processOperator(PDFStreamEngine.java:798)
        at com.tom_roush.pdfbox.contentstream.PDFStreamEngine.processStreamOperators(PDFStreamEngine.java:460)
        at com.tom_roush.pdfbox.contentstream.PDFStreamEngine.processStream(PDFStreamEngine.java:437)
11-29 15:02:44.020 6345-6345/com.tom_roush.pdfbox.sample W/System.err:     at com.tom_roush.pdfbox.contentstream.PDFStreamEngine.processPage(PDFStreamEngine.java:146)
        at com.tom_roush.pdfbox.rendering.PageDrawer.drawPage(PageDrawer.java:153)
        at com.tom_roush.pdfbox.rendering.PDFRenderer.renderPage(PDFRenderer.java:151)
        at com.tom_roush.pdfbox.rendering.PDFRenderer.renderImage(PDFRenderer.java:113)
        at com.tom_roush.pdfbox.sample.MainActivity.renderFile(MainActivity.java:156)
        at java.lang.reflect.Method.invoke(Native Method)
        at android.view.View$DeclaredOnClickListener.onClick(View.java:5684)
        at android.view.View.performClick(View.java:6897)
        at android.widget.TextView.performClick(TextView.java:12693)
        at android.view.View$PerformClick.run(View.java:26101)
11-29 15:02:44.021 6345-6345/com.tom_roush.pdfbox.sample W/System.err:     at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
11-29 15:02:44.054 6345-6355/com.tom_roush.pdfbox.sample W/PdfBox-Android: Warning: You did not close a PDF Document

**Comment by ToysoftInc** [comment]
I did some investigation it appears the gradle library is older than the library source that is included.
When compiled with the library it is not crashing now but only the first Annotation few ink strokes are shown and the rest are not.

**Comment by TomRoush** [comment]
The fix for this issue has been included in the v1.8.10.1 release.
