### ISSUE TITLE
when try to  fill w9form (multiple TextField) application is crashed / errors happend

### ISSUE THREAD

**Issue by darktheft** [TomRoush/PdfBox-Android#233]
2020-11-20 13:52:45.472 19643-19643/? D/PdfBox-Android: parsed=COSObject{811, 0}
2020-11-20 13:52:45.473 19643-19643/? D/PdfBox-Android: parsed=COSObject{812, 0}
2020-11-20 13:52:45.473 19643-19643/? D/PdfBox-Android: parsed=COSObject{813, 0}
2020-11-20 13:52:45.473 19643-19643/? D/PdfBox-Android: parsed=COSObject{814, 0}
2020-11-20 13:52:45.579 19643-19643/? D/AndroidRuntime: Shutting down VM
2020-11-20 13:52:45.581 19643-19643/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.tom_roush.pdfbox.sample, PID: 19643
    java.lang.IllegalStateException: Could not execute method for android:onClick
        at android.view.View$DeclaredOnClickListener.onClick(View.java:6268)
        at android.view.View.performClick(View.java:7448)
        at android.view.View.performClickInternal(View.java:7425)
        at android.view.View.access$3600(View.java:810)
        at android.view.View$PerformClick.run(View.java:28305)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at android.view.View$DeclaredOnClickListener.onClick(View.java:6263)
        at android.view.View.performClick(View.java:7448) 
        at android.view.View.performClickInternal(View.java:7425) 
        at android.view.View.access$3600(View.java:810) 
        at android.view.View$PerformClick.run(View.java:28305) 
        at android.os.Handler.handleCallback(Handler.java:938) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:223) 
        at android.app.ActivityThread.main(ActivityThread.java:7656) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947) 
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.tom_roush.pdfbox.pdmodel.interactive.form.PDTextField.setValue(java.lang.String)' on a null object reference
        at com.tom_roush.pdfbox.sample.MainActivity.fillForm(MainActivity.java:251)

and in activity:---

try{

  PDDocument document = PDDocument.load(assetManager.open("fw9.pdf"));
            PDDocumentCatalog docCatalog = document.getDocumentCatalog();
            PDAcroForm acroForm = docCatalog.getAcroForm();

 String  _5_1 = "TextField[0].Page1[0].Name[0]";
            // Fill the text field
            PDTextField field = (PDTextField) acroForm.getField(_5_1);
            field.setValue("laxmi kant ");
 PDField checkbox = acroForm.getField("Checkbox");
            ((PDCheckbox) checkbox).setValue("second");

            String path = root.getAbsolutePath() + "/FilledForm.pdf";
            tv.setText("Saved filled form to " + path);
            document.save(path);
            document.close();
        } catch (IOException e) {
            Log.e("PdfBox-Android-Sample", "Exception thrown while filling form fields", e);
        }

**Comment by darktheft** [comment]
try {
            File f = new File(getIntent().getExtras().getString("file"));
            pdfView.fromFile(f).load();
        } catch (Exception ex) {
            Log.e("new activity error", getIntent().getExtras().getString("file"));
        }


        buttonGetSignature.setOnClickListener(new View.OnClickListener() {
            public void onClick(View v) {
                Intent intent = new Intent(ShowDocumentActivity.this, GetSignatureActivity.class);
                intent.putExtra("file", getIntent().getExtras().getString("file"));
                intent.putExtra("source", getIntent().getExtras().getString("source"));
                startActivity(intent);
                finish();
            }
        });
store in locally and put them next screen using Intent
