### ISSUE TITLE
Crashes in Android App

### ISSUE THREAD

**Issue by vanniktech** [TomRoush/PdfBox-Android#261]
Hey, I've integrated this library into one of my Android apps: https://play.google.com/store/apps/details?id=com.vanniktech.speedreading&hl=en&gl=US

However, I'm getting quite a few crashes every now and then. How would you like me to report them? I can give you stacktraces. I don't have access to the PDF files though, so I don't know how much help stacktraces would be.

**Comment by vanniktech** [comment]
One such example with Version 1.8.10.3 is:

```
Non-fatal Exception: java.io.IOException: Error reading stream, expected='endstream' actual='' at offset 1605632
       at com.tom_roush.pdfbox.pdfparser.COSParser.parseCOSStream(COSParser.java:994)
       at com.tom_roush.pdfbox.pdfparser.COSParser.parseFileObject(COSParser.java:767)
       at com.tom_roush.pdfbox.pdfparser.COSParser.parseObjectDynamically(COSParser.java:727)
       at com.tom_roush.pdfbox.pdfparser.COSParser.parseObjectDynamically(COSParser.java:656)
       at com.tom_roush.pdfbox.pdfparser.COSParser.parseDictObjects(COSParser.java:617)
       at com.tom_roush.pdfbox.pdfparser.PDFParser.initialParse(PDFParser.java:237)
       at com.tom_roush.pdfbox.pdfparser.PDFParser.parse(PDFParser.java:264)
       at com.tom_roush.pdfbox.pdmodel.PDDocument.load(PDDocument.java:1078)
       at com.tom_roush.pdfbox.pdmodel.PDDocument.load(PDDocument.java:945)
```

**Comment by TomRoush** [comment]
This sounds like a PDF specific issue, but the stack traces are better than nothing. This specific Exception seems to be caused by a truncated PDF. you might have better luck with these kinds of exceptions when the library is updated to be based on a newer version of PDFBox

**Comment by vanniktech** [comment]
Another with 1.8.10.3:

```
Non-fatal Exception: java.io.IOException: Error getting header version: %PDF-1.4]
       at com.tom_roush.pdfbox.pdfparser.COSParser.parseHeader(COSParser.java:1943)
       at com.tom_roush.pdfbox.pdfparser.COSParser.parsePDFHeader(COSParser.java:1860)
       at com.tom_roush.pdfbox.pdfparser.PDFParser.parse(PDFParser.java:257)
       at com.tom_roush.pdfbox.pdmodel.PDDocument.load(PDDocument.java:1078)
       at com.tom_roush.pdfbox.pdmodel.PDDocument.load(PDDocument.java:945)
```

**Comment by TomRoush** [comment]
@vanniktech if possible, can you share your PDF on #266?

**Comment by vanniktech** [comment]
@TomRoush I wish I could but currently I don't have access to the PDF. I might be able to work around that by letting the user email me the PDF

**Comment by vanniktech** [comment]
I've added an option for the user to send me the pdf via email but so far no one has done that. There's a new crash though:

```
Non-fatal Exception: java.lang.ClassCastException: com.tom_roush.pdfbox.cos.COSInteger cannot be cast to com.tom_roush.pdfbox.cos.COSArray
       at com.tom_roush.pdfbox.contentstream.operator.text.ShowTextAdjusted.process(ShowTextAdjusted.java:37)
       at com.tom_roush.pdfbox.contentstream.PDFStreamEngine.processOperator(PDFStreamEngine.java:798)
       at com.tom_roush.pdfbox.contentstream.PDFStreamEngine.processStreamOperators(PDFStreamEngine.java:460)
       at com.tom_roush.pdfbox.contentstream.PDFStreamEngine.processStream(PDFStreamEngine.java:437)
       at com.tom_roush.pdfbox.contentstream.PDFStreamEngine.processPage(PDFStreamEngine.java:146)
       at com.tom_roush.pdfbox.text.PDFTextStreamEngine.processPage(PDFTextStreamEngine.java:123)
       at com.tom_roush.pdfbox.text.PDFTextStripper.processPage(PDFTextStripper.java:370)
       at com.tom_roush.pdfbox.text.PDFTextStripper.processPages(PDFTextStripper.java:306)
       at com.tom_roush.pdfbox.text.PDFTextStripper.writeText(PDFTextStripper.java:251)
       at com.tom_roush.pdfbox.text.PDFTextStripper.getText(PDFTextStripper.java:212)
       at com.vanniktech.feature.speedreading.SpeedReadingInsertionView$handleFile$2.invoke(SpeedReadingInsertionView.kt:148)
       at com.vanniktech.feature.speedreading.SpeedReadingInsertionView$handleFile$2.invoke(SpeedReadingInsertionView.kt:145)
       at com.vanniktech.feature.speedreading.SpeedReadingInsertionView.readFrom$lambda-5(SpeedReadingInsertionView.kt:179)
       at com.vanniktech.feature.speedreading.SpeedReadingInsertionView.lambda$-7vPHrl8QtYAbA25f1m9omtulbo()
       at com.vanniktech.feature.speedreading.-$$Lambda$SpeedReadingInsertionView$-7vPHrl8QtYAbA25f1m9omtulbo.call(:4)
       at io.reactivex.internal.operators.single.SingleFromCallable.subscribeActual(SingleFromCallable.java:44)
       at io.reactivex.Single.subscribe(Single.java:3666)
       at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
       at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:608)
       at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
       at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
```

**Comment by vanniktech** [comment]
Update to 2.x helped reducing the crashes. If I encounter any, I'll post a new issue
