### ISSUE TITLE
PdfBox-Android: Can't parse the header version.

### ISSUE THREAD

**Issue by notchdesign** [TomRoush/PdfBox-Android#266]
I am trying to render PDF using PdfBox but sometimes I am getting this error when the PDF only contains scanned images. It is happening when I am trying to load data using `PDDocument.load(doc.pdf)`

```
D/PdfBox-Android: Can't parse the header version.
    java.lang.NumberFormatException: For input string: "1.4 Sharp Scanned ImagePDF"
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
        at sun.misc.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
        at java.lang.Float.parseFloat(Float.java:451)
        at com.tom_roush.pdfbox.pdfparser.COSParser.parseHeader(COSParser.java:1934)
        at com.tom_roush.pdfbox.pdfparser.COSParser.parsePDFHeader(COSParser.java:1860)
        at com.tom_roush.pdfbox.pdfparser.PDFParser.parse(PDFParser.java:257)
        at com.tom_roush.pdfbox.pdmodel.PDDocument.load(PDDocument.java:1078)
        at com.tom_roush.pdfbox.pdmodel.PDDocument.load(PDDocument.java:945)
        at com.eyecan.app.activities.ReadPdfActivity.readFromUri(ReadPdfActivity.java:270)
        at com.eyecan.app.activities.ReadPdfActivity.onCreate(ReadPdfActivity.java:122)
        at android.app.Activity.performCreate(Activity.java:7955)
        at android.app.Activity.performCreate(Activity.java:7944)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3531)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3703)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2216)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:237)
        at android.app.ActivityThread.main(ActivityThread.java:7948)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
```

**Comment by TomRoush** [comment]
Can you share a PDF with this problem? From the exception it sounds like the PDF has an invalid version set, but there could be a bug in the parsing
