### ISSUE TITLE
Error: Could not find referenced cmap stream Identity-H

### ISSUE THREAD

**Issue by markusressel** [TomRoush/PdfBox-Android#293]
When trying to load a font file, the following error shows up:

```
    java.io.IOException: Error: Could not find referenced cmap stream Identity-H
        at com.tom_roush.fontbox.cmap.CMapParser.getExternalCMap(CMapParser.java:421)
        at com.tom_roush.fontbox.cmap.CMapParser.parsePredefined(CMapParser.java:88)
        at com.tom_roush.pdfbox.pdmodel.font.CMapManager.getPredefinedCMap(CmapManager.java:54)
        at com.tom_roush.pdfbox.pdmodel.font.PDType0Font.readEncoding(PDType0Font.java:182)
        at com.tom_roush.pdfbox.pdmodel.font.PDType0Font.<init>(PDType0Font.java:142)
        at com.tom_roush.pdfbox.pdmodel.font.PDType0Font.load(PDType0Font.java:78)
```

I am using this code:
```
val font = PDType0Font.load(this, resources.assets.open(FONT_FILE))
```

where `FONT_FILE` is the name of a font file in the assets folder.
The font is `Roboto-Regular.ttf`.

This did work with the last 1.8.x.x version, but doesn't work anymore with 2.0.0.0

**Comment by markusressel** [comment]
Calling

```
PDFBoxResourceLoader.init(resources)
```

as mentioned in the v2.0.0.0 migration hints fixed the issue.
