### ISSUE TITLE
NullPointerException while saving PDDocument

### ISSUE THREAD

**Issue by noirtier-villefort** [TomRoush/PdfBox-Android#348]
Code snippet to reproduce the behavior:
```
public File save(String documentText, String name) {
        File file = new File(context.getFilesDir()+"/"+name);

        PDDocument document = new PDDocument();

        PDPage page = new PDPage();
        document.addPage(page);

        try {
            PDPageContentStream contentStream = new PDPageContentStream(document, page);

            contentStream.setFont(PDType0Font.load(null, context.getAssets().open("times-new-roman.ttf")), FONT_SIZE);
            contentStream.setNonStrokingColor(15,37,192);
            contentStream.setLeading(LEADING);

            String[] linedText = documentText.split("\n");
            int linesCount=0;

            contentStream.beginText();
            for(String textLine: linedText){
                if(linesCount==25){
                    contentStream.endText();
                    contentStream.close();
                    linesCount=0;
                    contentStream = returnNewPageContent(document);
                }

                writeLine(document, contentStream, textLine);
                linesCount+=1;
            }
            contentStream.endText();
            contentStream.close();

            document.save(file);
            document.close();

        } catch (IOException e) {
            e.printStackTrace();
        }

        return file;
    }


    private PDPageContentStream returnNewPageContent(PDDocument doc) throws IOException {
        PDPage page = new PDPage();
        doc.addPage(page);
        PDPageContentStream contentStream = new PDPageContentStream(doc, page);
        contentStream.setFont(PDType0Font.load(null, context.getAssets().open("times-new-roman.ttf")), FONT_SIZE);
        contentStream.setLeading(LEADING);
        contentStream.beginText();
        contentStream.newLineAtOffset(25, 700);
        return contentStream;
    }
```

**Expected behavior**
Saving multilined text in PDF 

**Actual behavior**
NullPointerException after saving while using custom cyryllic font

**Environment details:**
 - PdfBox-Android version: 2.0.10.0
 - Android API version: 23 

**Additional context**
```
java.lang.NullPointerException: Attempt to invoke virtual method 'com.tom_roush.pdfbox.cos.COSDocument com.tom_roush.pdfbox.pdmodel.PDDocument.getDocument()' on a null object reference
        at com.tom_roush.pdfbox.pdmodel.common.PDStream.<init>(PDStream.java:131)
        at com.tom_roush.pdfbox.pdmodel.common.PDStream.<init>(PDStream.java:105)
        at com.tom_roush.pdfbox.pdmodel.font.PDCIDFontType2Embedder.buildToUnicodeCMap(PDCIDFontType2Embedder.java:170)
        at com.tom_roush.pdfbox.pdmodel.font.PDCIDFontType2Embedder.buildSubset(PDCIDFontType2Embedder.java:114)
        at com.tom_roush.pdfbox.pdmodel.font.TrueTypeEmbedder.subset(TrueTypeEmbedder.java:341)
        at com.tom_roush.pdfbox.pdmodel.font.PDType0Font.subset(PDType0Font.java:238)
        at com.tom_roush.pdfbox.pdmodel.PDDocument.save(PDDocument.java:1257)
        at com.tom_roush.pdfbox.pdmodel.PDDocument.save(PDDocument.java:1236)
       ...
```
Font that i use : https://file.io/0g2kLwsRa00h

**Comment by noirtier-villefort** [comment]
My mistake. I passed null document in returnNewPageContent
