### ISSUE TITLE
Getting text causes StackOverflowError on Android 5 and 6

### ISSUE THREAD

**Issue by kreativityapps** [TomRoush/PdfBox-Android#442]
**Describe the bug**
Trying to extract text from any pdf on Android 5 and 6 causes StackOverflowError.

**To reproduce**
Code snippet to reproduce the behaviour:
```
pdfTextStripper.getText(doc)
```
**PDF example**
[exmaple pdf](https://www.africau.edu/images/default/sample.pdf)

**Expected behavior**
Text is extracted without a crash.

**Actual behavior**
Crashes.
<details>
  <summary>Crash log at com.tom_roush.fontbox.ttf.BufferedRandomAccessFile.read</summary>
  
> Fatal Exception: java.lang.StackOverflowError: stack size 1036KB
       at com.tom_roush.fontbox.ttf.BufferedRandomAccessFile.read(BufferedRandomAccessFile.java)
       at java.io.RandomAccessFile.read(RandomAccessFile.java:269)
       at com.tom_roush.fontbox.ttf.BufferedRandomAccessFile.fillBuffer(BufferedRandomAccessFile.java)
       at com.tom_roush.fontbox.ttf.BufferedRandomAccessFile.read(BufferedRandomAccessFile.java)
       at java.io.RandomAccessFile.read(RandomAccessFile.java:269)
       at com.tom_roush.fontbox.ttf.BufferedRandomAccessFile.fillBuffer(BufferedRandomAccessFile.java)
       at com.tom_roush.fontbox.ttf.BufferedRandomAccessFile.read(BufferedRandomAccessFile.java)
       at java.io.RandomAccessFile.read(RandomAccessFile.java:269)
       at com.tom_roush.fontbox.ttf.BufferedRandomAccessFile.fillBuffer(BufferedRandomAccessFile.java)
       at com.tom_roush.fontbox.ttf.BufferedRandomAccessFile.read(BufferedRandomAccessFile.java)
       at java.io.RandomAccessFile.read(RandomAccessFile.java:269)
       at com.tom_roush.fontbox.ttf.BufferedRandomAccessFile.fillBuffer(BufferedRandomAccessFile.java)
       at com.tom_roush.fontbox.ttf.BufferedRandomAccessFile.read(BufferedRandomAccessFile.java)
       at java.io.RandomAccessFile.read(RandomAccessFile.java:269)
       at com.tom_roush.fontbox.ttf.BufferedRandomAccessFile.fillBuffer(BufferedRandomAccessFile.java)
       at com.tom_roush.fontbox.ttf.BufferedRandomAccessFile.read(BufferedRandomAccessFile.java)
       at java.io.RandomAccessFile.read(RandomAccessFile.java:269)
       at com.tom_roush.fontbox.ttf.BufferedRandomAccessFile.fillBuffer(BufferedRandomAccessFile.java)
       at com.tom_roush.fontbox.ttf.BufferedRandomAccessFile.read(BufferedRandomAccessFile.java)
       at java.io.RandomAccessFile.read(RandomAccessFile.java:269)
       at com.tom_roush.fontbox.ttf.BufferedRandomAccessFile.fillBuffer(BufferedRandomAccessFile.java)
       at com.tom_roush.fontbox.ttf.BufferedRandomAccessFile.read(BufferedRandomAccessFile.java)
       at java.io.RandomAccessFile.read(RandomAccessFile.java:269)
       at com.tom_roush.fontbox.ttf.BufferedRandomAccessFile.fillBuffer(BufferedRandomAccessFile.java)
       at com.tom_roush.fontbox.ttf.BufferedRandomAccessFile.read(BufferedRandomAccessFile.java)
       at java.io.RandomAccessFile.read(RandomAccessFile.java:269)
       at com.tom_roush.fontbox.ttf.BufferedRandomAccessFile.fillBuffer(BufferedRandomAccessFile.java)
       at com.tom_roush.fontbox.ttf.BufferedRandomAccessFile.read(BufferedRandomAccessFile.java)
       at java.io.RandomAccessFile.read(RandomAccessFile.java:269)
       at com.tom_roush.fontbox.ttf.BufferedRandomAccessFile.fillBuffer(BufferedRandomAccessFile.java)
       at com.tom_roush.fontbox.ttf.BufferedRandomAccessFile.read(BufferedRandomAccessFile.java)
       at java.io.RandomAccessFile.readFully(RandomAccessFile.java:413)
       at java.io.RandomAccessFile.readShort(RandomAccessFile.java:513)
       at com.tom_roush.fontbox.ttf.RAFDataStream.readSignedShort(RAFDataStream.java)
       at com.tom_roush.fontbox.ttf.TTFDataStream.read32Fixed(TTFDataStream.java)
       at com.tom_roush.fontbox.ttf.TTFParser.parse(TTFParser.java)
       at com.tom_roush.fontbox.ttf.TTFParser.parse(TTFParser.java)
       at com.tom_roush.pdfbox.pdmodel.font.FileSystemFontProvider.addTrueTypeFont(FileSystemFontProvider.java)
       at com.tom_roush.pdfbox.pdmodel.font.FileSystemFontProvider.<init>(FileSystemFontProvider.java)
       at com.tom_roush.pdfbox.pdmodel.font.FontMapperImpl$DefaultFontProvider.<clinit>(FontMapperImpl.java)
       at com.tom_roush.pdfbox.pdmodel.font.FontMapperImpl.getProvider(FontMapperImpl.java)
       at com.tom_roush.pdfbox.pdmodel.font.FontMapperImpl.findFont(FontMapperImpl.java)
       at com.tom_roush.pdfbox.pdmodel.font.FontMapperImpl.getTrueTypeFont(FontMapperImpl.java)
       at com.tom_roush.pdfbox.pdmodel.font.PDTrueTypeFont.<init>(PDTrueTypeFont.java)
       at com.tom_roush.pdfbox.pdmodel.font.PDFontFactory.createFont(PDFontFactory.java)
       at com.tom_roush.pdfbox.pdmodel.PDResources.getFont(PDResources.java)
       at com.tom_roush.pdfbox.contentstream.operator.text.SetFontAndSize.process(SetFontAndSize.java)
       at com.tom_roush.pdfbox.contentstream.PDFStreamEngine.processOperator(PDFStreamEngine.java)
       at com.tom_roush.pdfbox.contentstream.PDFStreamEngine.processStreamOperators(PDFStreamEngine.java)
       at com.tom_roush.pdfbox.contentstream.PDFStreamEngine.processStream(PDFStreamEngine.java)
       at com.tom_roush.pdfbox.contentstream.PDFStreamEngine.processPage(PDFStreamEngine.java)
       at com.tom_roush.pdfbox.text.LegacyPDFStreamEngine.processPage(LegacyPDFStreamEngine.java)
       at com.tom_roush.pdfbox.text.PDFTextStripper.processPage(PDFTextStripper.java)
       at com.tom_roush.pdfbox.text.PDFTextStripper.processPages(PDFTextStripper.java)
       at com.tom_roush.pdfbox.text.PDFTextStripper.writeText(PDFTextStripper.java)
       at com.tom_roush.pdfbox.text.PDFTextStripper.getText(PDFTextStripper.java)
       at dev.aluc.pdf_text.PdfTextPlugin.initTextStripperEngine(PdfTextPlugin.java)
       at dev.aluc.pdf_text.PdfTextPlugin.getDoc(PdfTextPlugin.java)
       at dev.aluc.pdf_text.PdfTextPlugin.initDoc(PdfTextPlugin.java)
       at dev.aluc.pdf_text.PdfTextPlugin.access$initDoc(PdfTextPlugin.java)
       at dev.aluc.pdf_text.PdfTextPlugin$onMethodCall$1.invoke(PdfTextPlugin.java)
       at dev.aluc.pdf_text.PdfTextPlugin$onMethodCall$1.invoke(PdfTextPlugin.java)
       at kotlin.concurrent.ThreadsKt$thread$thread$1.run(ThreadsKt.java)
</details>

<details>
  <summary>Crash log at com.tom_roush.fontbox.ttf.BufferedRandomAccessFile.fillBuffer</summary>

> Fatal Exception: java.lang.StackOverflowError: stack size 1038KB
       at java.io.RandomAccessFile.read(RandomAccessFile.java:272)
       at com.tom_roush.fontbox.ttf.BufferedRandomAccessFile.fillBuffer(BufferedRandomAccessFile.java)
       at com.tom_roush.fontbox.ttf.BufferedRandomAccessFile.read(BufferedRandomAccessFile.java)
       at java.io.RandomAccessFile.read(RandomAccessFile.java:272)
       at com.tom_roush.fontbox.ttf.BufferedRandomAccessFile.fillBuffer(BufferedRandomAccessFile.java)
       at com.tom_roush.fontbox.ttf.BufferedRandomAccessFile.read(BufferedRandomAccessFile.java)
       at java.io.RandomAccessFile.read(RandomAccessFile.java:272)
       at com.tom_roush.fontbox.ttf.BufferedRandomAccessFile.fillBuffer(BufferedRandomAccessFile.java)
       at com.tom_roush.fontbox.ttf.BufferedRandomAccessFile.read(BufferedRandomAccessFile.java)
       at java.io.RandomAccessFile.read(RandomAccessFile.java:272)
       at com.tom_roush.fontbox.ttf.BufferedRandomAccessFile.fillBuffer(BufferedRandomAccessFile.java)
       at com.tom_roush.fontbox.ttf.BufferedRandomAccessFile.read(BufferedRandomAccessFile.java)
       at java.io.RandomAccessFile.read(RandomAccessFile.java:272)
       at com.tom_roush.fontbox.ttf.BufferedRandomAccessFile.fillBuffer(BufferedRandomAccessFile.java)
       at com.tom_roush.fontbox.ttf.BufferedRandomAccessFile.read(BufferedRandomAccessFile.java)
       at java.io.RandomAccessFile.read(RandomAccessFile.java:272)
       at com.tom_roush.fontbox.ttf.BufferedRandomAccessFile.fillBuffer(BufferedRandomAccessFile.java)
       at com.tom_roush.fontbox.ttf.BufferedRandomAccessFile.read(BufferedRandomAccessFile.java)
       at java.io.RandomAccessFile.read(RandomAccessFile.java:272)
       at com.tom_roush.fontbox.ttf.BufferedRandomAccessFile.fillBuffer(BufferedRandomAccessFile.java)
       at com.tom_roush.fontbox.ttf.BufferedRandomAccessFile.read(BufferedRandomAccessFile.java)
       at java.io.RandomAccessFile.read(RandomAccessFile.java:272)
       at com.tom_roush.fontbox.ttf.BufferedRandomAccessFile.fillBuffer(BufferedRandomAccessFile.java)
       at com.tom_roush.fontbox.ttf.BufferedRandomAccessFile.read(BufferedRandomAccessFile.java)
       at java.io.RandomAccessFile.read(RandomAccessFile.java:272)
       at com.tom_roush.fontbox.ttf.BufferedRandomAccessFile.fillBuffer(BufferedRandomAccessFile.java)
       at com.tom_roush.fontbox.ttf.BufferedRandomAccessFile.read(BufferedRandomAccessFile.java)
       at java.io.RandomAccessFile.read(RandomAccessFile.java:272)
       at com.tom_roush.fontbox.ttf.BufferedRandomAccessFile.fillBuffer(BufferedRandomAccessFile.java)
       at com.tom_roush.fontbox.ttf.BufferedRandomAccessFile.read(BufferedRandomAccessFile.java)
       at java.io.RandomAccessFile.readFully(RandomAccessFile.java:416)
       at java.io.RandomAccessFile.readShort(RandomAccessFile.java:516)
       at com.tom_roush.fontbox.ttf.RAFDataStream.readSignedShort(RAFDataStream.java)
       at com.tom_roush.fontbox.ttf.TTFDataStream.read32Fixed(TTFDataStream.java)
       at com.tom_roush.fontbox.ttf.TTFParser.parse(TTFParser.java)
       at com.tom_roush.fontbox.ttf.TTFParser.parse(TTFParser.java)
       at com.tom_roush.pdfbox.pdmodel.font.FileSystemFontProvider.addTrueTypeFont(FileSystemFontProvider.java)
       at com.tom_roush.pdfbox.pdmodel.font.FileSystemFontProvider.<init>(FileSystemFontProvider.java)
       at com.tom_roush.pdfbox.pdmodel.font.FontMapperImpl$DefaultFontProvider.<clinit>(FontMapperImpl.java)
       at com.tom_roush.pdfbox.pdmodel.font.FontMapperImpl.getProvider(FontMapperImpl.java)
       at com.tom_roush.pdfbox.pdmodel.font.FontMapperImpl.findFont(FontMapperImpl.java)
       at com.tom_roush.pdfbox.pdmodel.font.FontMapperImpl.findFontBoxFont(FontMapperImpl.java)
       at com.tom_roush.pdfbox.pdmodel.font.FontMapperImpl.getFontBoxFont(FontMapperImpl.java)
       at com.tom_roush.pdfbox.pdmodel.font.PDType1Font.<init>(PDType1Font.java)
       at com.tom_roush.pdfbox.pdmodel.font.PDType1Font.<clinit>(PDType1Font.java)
       at com.tom_roush.pdfbox.pdmodel.font.PDFontFactory.createFont(PDFontFactory.java)
       at com.tom_roush.pdfbox.pdmodel.PDResources.getFont(PDResources.java)
       at com.tom_roush.pdfbox.contentstream.operator.text.SetFontAndSize.process(SetFontAndSize.java)
       at com.tom_roush.pdfbox.contentstream.PDFStreamEngine.processOperator(PDFStreamEngine.java)
       at com.tom_roush.pdfbox.contentstream.PDFStreamEngine.processStreamOperators(PDFStreamEngine.java)
       at com.tom_roush.pdfbox.contentstream.PDFStreamEngine.processStream(PDFStreamEngine.java)
       at com.tom_roush.pdfbox.contentstream.PDFStreamEngine.processPage(PDFStreamEngine.java)
       at com.tom_roush.pdfbox.text.LegacyPDFStreamEngine.processPage(LegacyPDFStreamEngine.java)
       at com.tom_roush.pdfbox.text.PDFTextStripper.processPage(PDFTextStripper.java)
       at com.tom_roush.pdfbox.text.PDFTextStripper.processPages(PDFTextStripper.java)
       at com.tom_roush.pdfbox.text.PDFTextStripper.writeText(PDFTextStripper.java)
       at com.tom_roush.pdfbox.text.PDFTextStripper.getText(PDFTextStripper.java)
       at dev.aluc.pdf_text.PdfTextPlugin.getDocText(PdfTextPlugin.java)
       at dev.aluc.pdf_text.PdfTextPlugin.access$getDocText(PdfTextPlugin.java)
       at dev.aluc.pdf_text.PdfTextPlugin$onMethodCall$1.invoke(PdfTextPlugin.java)
       at dev.aluc.pdf_text.PdfTextPlugin$onMethodCall$1.invoke(PdfTextPlugin.java)
       at kotlin.concurrent.ThreadsKt$thread$thread$1.run(ThreadsKt.java)
</details>

**Environment details:**
 - PdfBox-Android version: 2.0.25.0
 - Android API version: API 22 and 23

**Additional context**
Several crashes in Crashlytics, also reproduced it locally on emulator.
They are old devices, however theoretically these API's are still supported.

**Comment by jk77** [comment]
This same StackOverflowError can be replicated by this statement:
`PDFont font = PDType1Font.HELVETICA_BOLD;`

Seen in API 19, 22, & 23.  No error in API 24 or 33.

**Comment by jk77** [comment]
This bug was introduced in PdfBox-Android version 2.0.25.0.  
The error does not occur in 2.0.24.0 and earlier versions.
