### ISSUE TITLE
PDFTextStripperByArea failed extracting text (font problems?)

### ISSUE THREAD

**Issue by roberto-naharro** [TomRoush/PdfBox-Android#5]
Hello,

I have tried the library with a lot of documents. It works fine but with some of them I got always a similar message:

```
11-06 14:59:34.737: E/PDResources(23440):   at java.lang.Thread.run(Thread.java:841)
11-06 14:59:34.737: W/PDTrueTypeFont(23440): Using fallback font for ArialMT
11-06 14:59:34.737: E/ExternalFonts(23440): No TTF fallback font for 'Helvetica'
11-06 14:59:34.737: W/PDTrueTypeFont(23440): Using fallback font for Tahoma
11-06 14:59:34.747: E/ExternalFonts(23440): No TTF fallback font for 'Helvetica'
11-06 14:59:34.747: W/PDTrueTypeFont(23440): Using fallback font for ArialNarrow
11-06 14:59:34.747: E/ExternalFonts(23440): No TTF fallback font for 'Helvetica'
11-06 14:59:34.747: W/PDTrueTypeFont(23440): Using fallback font for ArialNarrow-BoldItalic
11-06 14:59:34.747: E/ExternalFonts(23440): No TTF fallback font for 'Helvetica-BoldOblique'
11-06 14:59:34.747: W/System.err(23440): java.io.IOException: Error: Could not find referenced cmap stream Identity-H
11-06 14:59:34.747: W/System.err(23440):    at org.apache.fontbox.cmap.CMapParser.getExternalCMap(CMapParser.java:383)
11-06 14:59:34.747: W/System.err(23440):    at org.apache.fontbox.cmap.CMapParser.parsePredefined(CMapParser.java:84)
11-06 14:59:34.747: W/System.err(23440):    at org.apache.pdfbox.pdmodel.font.CMapManager.getPredefinedCMap(CmapManager.java:34)
11-06 14:59:34.747: W/System.err(23440):    at org.apache.pdfbox.pdmodel.font.PDType0Font.readEncoding(PDType0Font.java:71)
11-06 14:59:34.747: W/System.err(23440):    at org.apache.pdfbox.pdmodel.font.PDType0Font.<init>(PDType0Font.java:48)
11-06 14:59:34.747: W/System.err(23440):    at org.apache.pdfbox.pdmodel.font.PDFontFactory.createFont(PDFontFactory.java:73)
11-06 14:59:34.747: W/System.err(23440):    at org.apache.pdfbox.pdmodel.PDResources.getFonts(PDResources.java:172)
11-06 14:59:34.747: W/System.err(23440):    at org.apache.pdfbox.contentstream.PDFStreamEngine.getFonts(PDFStreamEngine.java:503)
11-06 14:59:34.747: W/System.err(23440):    at org.apache.pdfbox.contentstream.operator.text.SetFontAndSize.process(SetFontAndSize.java:32)
11-06 14:59:34.747: W/System.err(23440):    at org.apache.pdfbox.contentstream.PDFStreamEngine.processOperator(PDFStreamEngine.java:466)
11-06 14:59:34.747: W/System.err(23440):    at org.apache.pdfbox.contentstream.PDFStreamEngine.processSubStream(PDFStreamEngine.java:220)
11-06 14:59:34.747: W/System.err(23440):    at org.apache.pdfbox.contentstream.PDFStreamEngine.processSubStream(PDFStreamEngine.java:185)
11-06 14:59:34.747: W/System.err(23440):    at org.apache.pdfbox.contentstream.PDFStreamEngine.processStream(PDFStreamEngine.java:139)
11-06 14:59:34.747: W/System.err(23440):    at org.apache.pdfbox.contentstream.PDFTextStreamEngine.processStream(PDFTextStreamEngine.java:105)
11-06 14:59:34.747: W/System.err(23440):    at org.apache.pdfbox.util.PDFTextStripper.processPage(PDFTextStripper.java:353)
11-06 14:59:34.747: W/System.err(23440):    at org.apache.pdfbox.util.PDFTextStripperByArea.extractRegions(PDFTextStripperByArea.java:102)
```

Sometimes is this message, and sometimes is "No fallback font for 'Helvetica'" or another font type

Is this a problem with this library, or maybe with PDFBox?

The code I have used is this:

```
PDFTextStripperByArea stripper = new PDFTextStripperByArea();

[...]
stripper.addRegion(k, regions_hash.get(k));
[...]

regions=stripper.getRegions();  
for(String region: regions) {
    String textForRegion = stripper.getTextForRegion(region);
    textForRegion=textForRegion.trim();

    if (!textForRegion.isEmpty()) {
        outStream.write((textForRegion+' ').getBytes());
    }
}
```

**Comment by rubdottocom** [comment]
Hi! I'm getting no TTF fallback warnings

`01-27 10:06:50.207   31485-1570/? E/ExternalFonts﹕ No TTF fallback font for 'Times-Roman'`

And I get this error with 1.8.8:

`Could not find referenced cmap stream Identity-H`

This is the code I made:

    File pdfFile = new File(mBookPath);

    PDFTextStripper textStripper = new PDFTextStripper();;
    PDDocument pdDoc = PDDocument.load(pdfFile);

    textStripper.setStartPage(1);
    textStripper.setEndPage(pdDoc.getNumberOfPages());

    String data = textStripper.getText(pdDoc);

So seems that PDFTextStripper fails too.

Are any of fixes proposed by @RainHeart257 merged in current version of PdfBox-Android? 

This is the book that fails: https://www.dropbox.com/s/urlhav4ze66kzmh/coffeescript%20copia.pdf?dl=0

**Comment by rubdottocom** [comment]
Another books that fails with 'Could not find referenced cmap stream Identity-H':

* https://www.dropbox.com/s/8k80rri2jj7stii/focus-en-espac3b1ol29.pdf?dl=0
* https://www.dropbox.com/s/4vm886itf976c7x/Referencia%20de%20plugins.pdf?dl=0

And this wants never ends to extract code, but I don't get errors.

* https://www.dropbox.com/s/vsk2oaqjcv7l28j/Remote_Control_Devices_es.pdf?dl=0

**Comment by Birdbrain2** [comment]
TTF fallback warnings should be fixed for all the fonts except for Times-Roman, I'm not sure why that font isn't. As far as I've been able to tell, it hasn't had any accept on function so far.

Identity-H was from something I messed up, it'll be fixed in the next update.

The TextStripper classes have issues that need to be worked on, and I'm not sure how long it will take to get it fixed. If you can, try some of the older jars. They may have TextStrippers that will work better for your pdfs.
