### ISSUE TITLE
I have my pdf file in assets, Error in rendering [pageImage = renderer.renderImage(0, 1, ImageType.RGB);]

### ISSUE THREAD

**Issue by SantoshJaya** [TomRoush/PdfBox-Android#562]
Caused by: java.lang.IllegalArgumentException: java.io.IOException: resource 'com/tom_roush/pdfbox/resources/afm/Times-Roman.afm' not found
                                                                                                    	at com.tom_roush.pdfbox.pdmodel.font.Standard14Fonts.getAFM(Standard14Fonts.java:198)
                                                                                                    	at com.tom_roush.pdfbox.pdmodel.font.PDFont.<init>(PDFont.java:90)
                                                                                                    	at com.tom_roush.pdfbox.pdmodel.font.PDSimpleFont.<init>(PDSimpleFont.java:62)
                                                                                                    	at com.tom_roush.pdfbox.pdmodel.font.PDType1Font.<init>(PDType1Font.java:120)
                                                                                                    	at com.tom_roush.pdfbox.pdmodel.font.PDType1Font.<clinit>(PDType1Font.java:77)
                                                                                                    	at com.tom_roush.pdfbox.pdmodel.font.PDFontFactory.createFont(PDFontFactory.java:74) 
                                                                                                    	at com.tom_roush.pdfbox.pdmodel.PDResources.getFont(PDResources.java:145) 
                                                                                                    	at com.tom_roush.pdfbox.contentstream.operator.text.SetFontAndSize.process(SetFontAndSize.java:62) 
                                                                                                    	at com.tom_roush.pdfbox.contentstream.PDFStreamEngine.processOperator(PDFStreamEngine.java:966) 
                                                                                                    	at com.tom_roush.pdfbox.contentstream.PDFStreamEngine.processStreamOperators(PDFStreamEngine.java:541) 
                                                                                                    	at com.tom_roush.pdfbox.contentstream.PDFStreamEngine.processStream(PDFStreamEngine.java:516) 
                                                                                                    	at com.tom_roush.pdfbox.contentstream.PDFStreamEngine.processPage(PDFStreamEngine.java:153) 
                                                                                                    	at com.tom_roush.pdfbox.rendering.PageDrawer.drawPage(PageDrawer.java:258) 
                                                                                                    	at com.tom_roush.pdfbox.rendering.PDFRenderer.renderImage(PDFRenderer.java:316) 
                                                                                                    	at com.tom_roush.pdfbox.rendering.PDFRenderer.renderImage(PDFRenderer.java:232) 
                                                                                                    	at in.co.visiontek.bt97_printer.MainActivity.renderFile(MainActivity.java:313) 
                                                                                                    	at in.co.visiontek.bt97_printer.MainActivity$7.onClick(MainActivity.java:227) 
                                                                                                    	at android.view.View.performClick(View.java:7455) 
                                                                                                    	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1218) 
                                                                                                    	at android.view.View.performClickInternal(View.java:7432) 
                                                                                                    	at android.view.View.access$3700(View.java:835) 
                                                                                                    	at android.view.View$PerformClick.run(View.java:28814) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201) 
                                                                                                    	at android.os.Looper.loop(Looper.java:288) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7911) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009) 
                                                                                                    Caused by: java.io.IOException: resource 'com/tom_roush/pdfbox/resources/afm/Times-Roman.afm' not found
                                                                                                    	at com.tom_roush.pdfbox.pdmodel.font.Standard14Fonts.loadMetrics(Standard14Fonts.java:129)
                                                                                                    	at com.tom_roush.pdfbox.pdmodel.font.Standard14Fonts.getAFM(Standard14Fonts.java:194)
                                                                                                    	at com.tom_roush.pdfbox.pdmodel.font.PDFont.<init>(PDFont.java:90) 
                                                                                                    	at com.tom_roush.pdfbox.pdmodel.font.PDSimpleFont.<init>(PDSimpleFont.java:62) 
                                                                                                    	at com.tom_roush.pdfbox.pdmodel.font.PDType1Font.<init>(PDType1Font.java:120) 
                                                                                                    	at com.tom_roush.pdfbox.pdmodel.font.PDType1Font.<clinit>(PDType1Font.java:77) 
                                                                                                    	at com.tom_roush.pdfbox.pdmodel.font.PDFontFactory.createFont(PDFontFactory.java:74) 
                                                                                                    	at com.tom_roush.pdfbox.pdmodel.PDResources.getFont(PDResources.java:145) 
                                                                                                    	at com.tom_roush.pdfbox.contentstream.operator.text.SetFontAndSize.process(SetFontAndSize.java:62) 
                                                                                                    	at com.tom_roush.pdfbox.contentstream.PDFStreamEngine.processOperator(PDFStreamEngine.java:966) 
                                                                                                    	at com.tom_roush.pdfbox.contentstream.PDFStreamEngine.processStreamOperators(PDFStreamEngine.java:541) 
                                                                                                    	at com.tom_roush.pdfbox.contentstream.PDFStreamEngine.processStream(PDFStreamEngine.java:516) 
                                                                                                    	at com.tom_roush.pdfbox.contentstream.PDFStreamEngine.processPage(PDFStreamEngine.java:153) 
                                                                                                    	at com.tom_roush.pdfbox.rendering.PageDrawer.drawPage(PageDrawer.java:258) 
                                                                                                    	at com.tom_roush.pdfbox.rendering.PDFRenderer.renderImage(PDFRenderer.java:316) 
                                                                                                    	at com.tom_roush.pdfbox.rendering.PDFRenderer.renderImage(PDFRenderer.java:232) 
                                                                                                    	at in.co.visiontek.bt97_printer.MainActivity.renderFile(MainActivity.java:313) 
                                                                                                    	at in.co.visiontek.bt97_printer.MainActivity$7.onClick(MainActivity.java:227) 
                                                                                                    	at android.view.View.performClick(View.java:7455) 
                                                                                                    	at com.google.android.material.button.MaterialButton.performClick(MaterialButton.java:1218) 
                                                                                                    	at android.view.View.performClickInternal(View.java:7432) 
                                                                                                    	at android.view.View.access$3700(View.java:835) 
                                                                                                    	at android.view.View$PerformClick.run(View.java:28814) 
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:201) 
                                                                                                    	at android.os.Looper.loop(Looper.java:288) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7911) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1009)

**Comment by SantoshJaya** [comment]
Forgot to initialize

 PDFBoxResourceLoader.init(getApplicationContext());
