### ISSUE TITLE
Crash when rendering PDF

### ISSUE THREAD

**Issue by ThePaulrBear** [TomRoush/PdfBox-Android#80]
I'm getting the following exception when I try to render PDFs. One of the PDFs that fails can be viewed [here.](https://github.com/TomRoush/PdfBox-Android/files/412229/adobe_test.pdf)

`E/AndroidRuntime: FATAL EXCEPTION: main
                  java.lang.NullPointerException
                      at android.graphics.Paint.setStrokeCap(Paint.java:772)
                      at org.apache.pdfbox.rendering.PageDrawer.setStroke(PageDrawer.java:504)
                      at org.apache.pdfbox.rendering.PageDrawer.strokePath(PageDrawer.java:519)
                      at org.apache.pdfbox.contentstream.operator.graphics.StrokePath.process(StrokePath.java:20)
                      at org.apache.pdfbox.contentstream.PDFStreamEngine.processOperator(PDFStreamEngine.java:802)
                      at org.apache.pdfbox.contentstream.PDFStreamEngine.processStreamOperators(PDFStreamEngine.java:464)
                      at org.apache.pdfbox.contentstream.PDFStreamEngine.processStream(PDFStreamEngine.java:438)
                      at org.apache.pdfbox.contentstream.PDFStreamEngine.processPage(PDFStreamEngine.java:147)
                      at org.apache.pdfbox.rendering.PageDrawer.drawPage(PageDrawer.java:118)
                      at org.apache.pdfbox.rendering.PDFRenderer.renderPage(PDFRenderer.java:124)
                      at org.apache.pdfbox.rendering.PDFRenderer.renderImage(PDFRenderer.java:87)
                      at org.apache.pdfbox.rendering.PDFRenderer.renderImage(PDFRenderer.java:43)
                      at com.paulwintz.helppage.PdfDocument.renderBitmapPage(PdfDocument.java:78)`

**Comment by TomRoush** [comment]
This might have been a problem with the old release. If you are still having this issue, can you try building from source or using the newest release?
