### ISSUE TITLE
not supported for Type 3 fonts

### ISSUE THREAD

**Issue by tsobeng** [TomRoush/PdfBox-Android#94]
Hi, 
I need to extract text from pdf input stream
here is the code
```
public String stripText(InputStream in) {
        String parsedText = null;
        PDDocument document = null;

        PDFBoxResourceLoader.init(getApplicationContext());
        try {
            document = PDDocument.load(in);
        } catch(IOException e) {
            e.printStackTrace();
            Log.d("stripText1", e.getMessage());
        }
        try {
            PDFTextStripper pdfStripper = new PDFTextStripper();
            pdfStripper.setStartPage(0);
            pdfStripper.setEndPage(1);
            parsedText = pdfStripper.getText(document);
        } catch (Exception e) {
            e.printStackTrace();
            Log.d("stripText2", e.getMessage());
        } finally {
            try {
                if (document != null) document.close();
            } catch (Exception e) {
                e.printStackTrace();
                Log.d("stripText3", e.getMessage());
            }
        }
        return parsedText;
    }
```
but when runing i got this error
```
W/System.err﹕ java.lang.UnsupportedOperationException: not supported for Type 3 fonts
W/System.err﹕ at com.tom_roush.pdfbox.pdmodel.font.PDType3Font.readEncodingFromFont(PDType3Font.java:50)
W/System.err﹕ at com.tom_roush.pdfbox.pdmodel.font.PDSimpleFont.readEncoding(PDSimpleFont.java:98)
W/System.err﹕ at com.tom_roush.pdfbox.pdmodel.font.PDType3Font.<init>(PDType3Font.java:38)
W/System.err﹕ at com.tom_roush.pdfbox.pdmodel.font.PDFontFactory.createFont(PDFontFactory.java:61)
W/System.err﹕ at com.tom_roush.pdfbox.pdmodel.PDResources.getFont(PDResources.java:76)
W/System.err﹕ at com.tom_roush.pdfbox.contentstream.operator.text.SetFontAndSize.process(SetFontAndSize.java:32)
W/System.err﹕ at com.tom_roush.pdfbox.contentstream.PDFStreamEngine.processOperator(PDFStreamEngine.java:802)
W/System.err﹕ at com.tom_roush.pdfbox.contentstream.PDFStreamEngine.processStreamOperators(PDFStreamEngine.java:464)
W/System.err﹕ at com.tom_roush.pdfbox.contentstream.PDFStreamEngine.processStream(PDFStreamEngine.java:438)
W/System.err﹕ at com.tom_roush.pdfbox.contentstream.PDFStreamEngine.processPage(PDFStreamEngine.java:147)
W/System.err﹕ at com.tom_roush.pdfbox.text.PDFTextStreamEngine.processPage(PDFTextStreamEngine.java:107)
W/System.err﹕ at com.tom_roush.pdfbox.text.PDFTextStripper.processPage(PDFTextStripper.java:334)
W/System.err﹕ at com.tom_roush.pdfbox.text.PDFTextStripper.processPages(PDFTextStripper.java:270)
W/System.err﹕ at com.tom_roush.pdfbox.text.PDFTextStripper.writeText(PDFTextStripper.java:235)
W/System.err﹕ at com.tom_roush.pdfbox.text.PDFTextStripper.getText(PDFTextStripper.java:194)
W/System.err﹕ at nhit.herbin.hprtprintservices.MyPrintService.stripText(MyPrintService.java:258)
W/System.err﹕ at nhit.herbin.hprtprintservices.MyPrintService.onPrintJobQueued(MyPrintService.java:179)
W/System.err﹕ at android.printservice.PrintService$ServiceHandler.handleMessage(PrintService.java:516)
W/System.err﹕ at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err﹕ at android.os.Looper.loop(Looper.java:136)
W/System.err﹕ at android.app.ActivityThread.main(ActivityThread.java:5590)
W/System.err﹕ at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err﹕ at java.lang.reflect.Method.invoke(Method.java:515)
W/System.err﹕ at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
W/System.err﹕ at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
W/System.err﹕ at dalvik.system.NativeStart.main(Native Method)
D/stripText2﹕ not supported for Type 3 fonts
```

I work with this in gradle file 
`compile 'com.tom_roush:pdfbox-android:1.8.9.1'`

What is the problem please? 
the pdf document look like this
![image](https://cloud.githubusercontent.com/assets/6357072/21500729/38063680-cc42-11e6-9775-2ab300203845.png)

**Comment by TomRoush** [comment]
Your looks fine and it seemed to work on my Type 3 font file. Are you able to share the actual PDF file for me to test on?

**Comment by tsobeng** [comment]
[OdooPOS4 (1).pdf](https://github.com/TomRoush/PdfBox-Android/files/678444/OdooPOS4.1.pdf)
This is the pdf file

**Comment by TomRoush** [comment]
This is a bug present in the desktop PdfBox at the version that PdfBox-Android is based on. Newer versions have had this issue fixed apparently, so it should be possible to fix this.

**Comment by THausherr** [comment]
I ran the ExtractText utility down from 1.8.13 to the 1.8.1 desktop version and it works.
